### PR TITLE
Fixes syntax of spec in if-let macro.

### PR DESCRIPTION
**Pull request by cniles**

### CODE REVIEW

**Comment by grimnebulin** [comment]
This isn't really a "fix," though, is it?  Just a difference of opinion about style.

**Comment by cniles** [comment]
Maybe? It was throwing an Elisp error for me without this change.

**Comment by cniles** [comment]
`(hmac 'sha256 "foo "bar")`

`hmac: Symbol’s function definition is void: blocksize`

Not too sure whats going on with the loading of the code that's causing to try pull the function for blocksize instead of treating it as a let binding form, but it looks like a me problem...

**Comment by cniles** [comment]
Re-compiling `hmac.el` as provided clears the error for me.

**Comment by grimnebulin** [comment]
I don't have much of an idea what the original problem was, but I'm glad you got it worked out.

**Pull request closed without merging**
